### ISSUE TITLE
Feature: Callback/event on note play

### ISSUE THREAD

**Issue by OscarWoHA** [jimutt/osmd-audio-player#2]
Hi! Awesome little project you've put together here. 

Haven't really dug too deep into your code yet, but I am in search of some sort of way of doing a number of things related to whenever a note is played/right before a note is played. 

A callback or event of some sort that I could attach to that provides me with the PlaybackEngine object  (or something along those lines) would be very much appreciated.

**Comment by jimutt** [comment]
Hi! Thanks, yes that could indeed be useful. I'll look into it. One small issue is that I currently schedule multiple notes in advance for the audio context. It is to ensure that the audio is not interrupted even if the main thread gets temporarily blocked by redraws due to scrolling or similar. But it would be possible to schedule events that "should" be emitted at the same time as the notes are played, but they might be slightly of by a couple of milliseconds sometimes. Or just emitting an event everytime new notes are scheduled.

**Comment by OscarWoHA** [comment]
Currently the only use case I've had for an event like this is to reset everything when the score is completely played. Basically a final timeout added that will trigger after the last note has been played.

**Comment by OscarWoHA** [comment]
I'm probably gonna sync up with the audio clock for the metronome I want to implement.

**Comment by conde2** [comment]
I’m also looking for this feature, very useful!

**Comment by jimutt** [comment]
Will be implemented in #11. :slightly_smiling_face:  But as mentioned due to the the buffered scheduling using AudioContext it's, at least with the current scheduler and playback logic, hard to achieve events that are fully synchronized with the audio clock.

**Comment by jimutt** [comment]
@OscarWoHA @conde2  if you use 0.4.1 you now have the possibility to subscribe to playback state & note playback events. 

You can check the basic demo that has been updated to console.log all iteration events. 

Will be looking into adding some other events in the future.

**Comment by conde2** [comment]
Thank you @jimutt !
