### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by grosmanjs** [jimutt/osmd-audio-player#27]
I'm using the player on Safari 13.1, and it's not working so well in this browser. When I try to execute the player, the console shows this message:

`ReferenceError: Can't find variable: AudioContext`

... I think that AudioContext needs to be replaced by the webkitAudioContext in Safari. The Player works when I explicit pass the proper AudioContext in the PlaybackEngine constructor but it crashes when I try to stop it:

![image](https://user-images.githubusercontent.com/5097052/88117117-a4de9080-cb90-11ea-8044-b0c8f3890406.png)

**Comment by jimutt** [comment]
Thanks for the information. I have not done any testing in Safari myself but it's not very surprising since there are currently no polyfilling at all applied for the dist build. A fix for the AudioContext constructor should be rather straight forward. Should be enough to apply a polyfill like https://github.com/shinnn/AudioContext-Polyfill. 

When it comes to the issues with the stop event it seems to be thrown from the dependency [soundfont-player](https://www.npmjs.com/package/soundfont-player). The plan is to move away from it though. 

The error source is likely related to Safari's behavior for AudioBufferSourceNodes. `stop()` is marked to have unknown behavior on Safari (https://developer.mozilla.org/en-US/docs/Web/API/AudioScheduledSourceNode/stop) and Safari seems to be quite strict to how it's allowed to be invoked: https://stackoverflow.com/a/59653104/1308385. In this case I think it's most likely being called for an object which hasn't been started yet. 

I'm afraid fixing that would need some extra logic to manage the audio nodes and keep track of which ones are in a state that allows stopping in Safari. I think it could be done in a more convenient way if I handled the more low level audio parts myself, which is one reason to the plan of moving away from soundfont-player. 

But I could look into it a bit more since the stop method is accepting specific audio notes to be passed in. So saving them after schedule and then keeping track of which nodes are stoppable instead of stopping all should supposedly solve it.

**Comment by jimutt** [comment]
@grosmanjs Will you please help me out with just verifying this supposed Safari fix? I've checked it in Browserstack and I think the initialization and stop events should be working: https://deploy-preview-32--osmd-audio-player-demo-vue.netlify.app/

**Comment by grosmanjs** [comment]
Hi @jimutt, it's working now. With your demo, I can play and stop without any problems :)
When are you planning to release this fix?

**Comment by jimutt** [comment]
Nice! Tried a few different options but found the standardized-audio-context package and decided to go with that. Seems like it solves most browser inconsistencies so no logic changes were needed. 

I'll merge it to master now but might not publish a new version to NPM right away, will have it done soon though. To use it immediately before a new version is released you can reference the Github URL in your package.json: 
```JSON
    "osmd-audio-player": "https://github.com/jimutt/osmd-audio-player/"
```

**Comment by grosmanjs** [comment]
Alright, thanks dude! :)

**Comment by jimutt** [comment]
@grosmanjs 0.6.0 is published to NPM now
